apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: 249153082193.dkr.ecr.us-east-1.amazonaws.com/api:latest
        name: api
        ports:
        - containerPort: 8080
        resources: {}
status: {}
