apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pinger
  name: pinger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinger
  strategy: {}
  template:
    metadata:
      labels:
        app: pinger
    spec:
      containers:
      - image: 249153082193.dkr.ecr.us-east-1.amazonaws.com/pinger:latest
        name: pinger
        resources: {}
status: {}
